name: Frontend Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: '1.0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Create archive
      working-directory: frontend
      run: tar -czvf sausage-store-${APP_VERSION}.${GITHUB_SHA:0:7}.tar.gz -C dist/frontend .

    - name: Upload frontend files
      uses: actions/upload-artifact@v3
      with:
        name: frontend-archive
        path: sausage-store-*.tar.gz
